name: glasskeep
services:
  glasskeep:
    image: nikunjsingh/glass-keep:latest
    container_name: glasskeep
    environment:
      - PORT=8080
      - ADMIN_EMAILS=admin@example.com
    network_mode: bridge
    ports:
      - target: 8080
        published: "3015"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/glasskeep/data
        target: /app/server/data
    x-casaos:
      ports:
        - container: "8080"
          description:
            en_us: "Web Port"
      volumes:
        - container: /app/server/data
          description:
            en_us: "Data Path"
x-casaos:
  architectures:
    - amd64
    - arm64
  main: glasskeep
  author: "Nikunj Singh"
  category: "Charlie"
  description:
    en_us: "A React-based Google Keep clone with glassmorphism UI."
  developer: "Nikunj Singh"
  icon: "https://raw.githubusercontent.com/nikunjsingh93/react-glass-keep/main/public/apple-touch-icon.png"
  tagline:
    en_us: "Sleek glass-designed notes."
  title:
    en_us: "Glass Keep"
  port_map: "3015"
  scheme: http
