name: redlib
services:
  redlib:
    container_name: redlib
    image: quay.io/redlib/redlib:latest
    restart: unless-stopped
    ports:
      - 4030:8080
    environment:
      - REDLIB_DEFAULT_THEME=ocean
      - REDLIB_DARK_MODE=on
    volumes:
      - /DATA/AppData/$AppID/data:/data
    network_mode: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm/v7
  main: redlib
  title:
    en_us: Redlib
  tagline:
    en_us: A private front-end for Reddit.
  description:
    en_us: Redlib is a private, lightweight front-end for Reddit, actively maintained and designed to be a direct, reliable replacement for Libreddit.
  developer: Redlib Contributors
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/redlib.png
  category: Charlie
  port_map: "4030"
